### ISSUE TITLE
2 Digit Hours do not display.

### ISSUE THREAD

**Issue by sgtwilko** [thearduinoguy/PiClock#1]
When the hours contain 2 digits the first digit is not shown on the clock.

**Comment by thearduinoguy** [comment]
Hmm.. I think it should be this before that as I believe the strftime("%l" will add a leading space to single digit hours...  

if currentDT.hour< 10:

**Comment by sgtwilko** [comment]
Pull request fixes it by trimming the leading space.
Doesn't need an `if` as it only trims if the space exists.
